pipeline {
  agent any
  stages {
    stage('Source') { // Get code
      steps {
        // get code from our Git repository
        git 'https://github.com/saurabh12j/DevOps-Demo-WebApp.git'
      }
    }
    stage('Build') { // Compile and do unit testing

      steps {
        // run Gradle to execute compile and unit testing
        sh 'mvn -B clean verify'
      }
    }
  }
}
