pipeline {
agent {
        docker {
            image 'maven:3-alpine' 
            args '-v /root/.m2:/root/.m2' 
        }
    }
  stages {
    stage('Source') { // Get code
      steps {
        // get code from our Git repository
        git 'https://github.com/saurabh12j/DevOps-Demo-WebApp.git'
      }
    }
    stage('Build') { // Compile and do unit testing

      steps {
        // run Gradle to execute compile and unit testing
        sh 'mvn -B -DskipTests clean package'
      }
    }
   stage('Test') { 
            steps {
                sh 'mvn test' 
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml' 
                }
            }       
  }
}
