pipeline {
agent any
    tools { 
        maven 'Maven'
        jdk 'jdk' 
    }
  stages {
    stage('Source') { // Get code
      steps {
        // get code from our Git repository
        git 'https://github.com/saurabh12j/DevOps-Demo-WebApp.git'
      }
    }
      
      stage ('SonarQube Analysis'){
steps{
//withSonarQubeEnv('sonarqube') {
//sh 'mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar'

sh 'mvn -Dsonar.test.exclusions=**/test/java/servlet/createpage_junit.java -Dsonar.login=admin -Dsonar.password=sonar -Dsonar.tests=. -Dsonar.inclusions=**/test/java/servlet/createpage_junit.java -Dsonar.sources=. sonar:sonar -Dsonar.host.url=http://52.152.224.93:9000'
}
} 
//}
    stage('Build') { // Compile and do unit testing

      steps {
        // run Gradle to execute compile and unit testing
        sh 'mvn -B -DskipTests clean compile'
      }
    }
      stage('Deploy - Test') { // Compile and do unit testing

      steps {
        // run Gradle to execute compile and unit testing
        sh 'mvn -B clean package'
      }
    }
stage('UI Test') { // Compile and do unit testing

      steps {
        // run Gradle to execute compile and unit testing
        sh 'mvn -B -f functionaltest/pom.xml test'
      }
    }

  }
}
